name: Generate Snake Animation

on:
  schedule: # Runs daily at midnight (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: NoamFav # Your GitHub username
          output: dist/github-contribution-grid-snake.svg
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/github-contribution-grid-snake.svg"
          message: "Updated Snake Animation"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
